// ----------------------------------------------------------------------------
// PixInsight JavaScript Runtime API - PJSR Version 1.0
// ----------------------------------------------------------------------------
// CoreIconsBrowser.js - Released 2019-01-19T18:43:13Z
// ----------------------------------------------------------------------------
//
// This file is part of Core Icons Browser Script version 1.14
//
// Copyright (c) 2013-2019 Pleiades Astrophoto S.L.
//
// Redistribution and use in both source and binary forms, with or without
// modification, is permitted provided that the following conditions are met:
//
// 1. All redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//
// 2. All redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//
// 3. Neither the names "PixInsight" and "Pleiades Astrophoto", nor the names
//    of their contributors, may be used to endorse or promote products derived
//    from this software without specific prior written permission. For written
//    permission, please contact info@pixinsight.com.
//
// 4. All products derived from this software, in any form whatsoever, must
//    reproduce the following acknowledgment in the end-user documentation
//    and/or other materials provided with the product:
//
//    "This product is based on software from the PixInsight project, developed
//    by Pleiades Astrophoto and its contributors (http://pixinsight.com/)."
//
//    Alternatively, if that is where third-party acknowledgments normally
//    appear, this acknowledgment must be reproduced in the product itself.
//
// THIS SOFTWARE IS PROVIDED BY PLEIADES ASTROPHOTO AND ITS CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
// TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL PLEIADES ASTROPHOTO OR ITS
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, BUSINESS
// INTERRUPTION; PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; AND LOSS OF USE,
// DATA OR PROFITS) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
// CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
// POSSIBILITY OF SUCH DAMAGE.
// ----------------------------------------------------------------------------

/*
 * PixInsight Core Icons Browser
 *
 * A script to browse PixInsight Core resource icons.
 *
 * Copyright (c) 2013-2019, Pleiades Astrophoto S.L. All Rights Reserved.
 * Written by Juan Conejero (PTeam)
 */

#feature-id    Development > Core Icons Browser

#feature-info  A utility script to browse PixInsight Core resource icons.<br/> \
   Written by Juan Conejero (PTeam)<br/>\
   Copyright &copy; 2013-2017 Pleiades Astrophoto, S.L.

#feature-icon  CoreIconsBrowser.xpm

#iflt __PI_BUILD__ 1457
#error This script requires PixInsight 1.8.6.1457 or higher.
#endif

#define VERSION "1.14"
#define TITLE   "Core Icons Browser"

#include <pjsr/Color.jsh>
#include <pjsr/Sizer.jsh>
#include <pjsr/Slider.jsh>
#include <pjsr/TextAlign.jsh>

#define MAX_ICON_SIZE 96

function IconBrowser()
{
   this.__base__ = Dialog;
   this.__base__();

   this.coreIcons =
   [
   /*
    * Automatically generated on 2019 January 19 for core version 1.8.6.1457
    */
":/appicon/pixinsight-bundle-icon.svg",
":/appicon/pixinsight-icon.svg",
":/arrows/arrow-bottom.png",
":/arrows/arrow-down-limit.png",
":/arrows/arrow-down.png",
":/arrows/arrow-left-limit.png",
":/arrows/arrow-left.png",
":/arrows/arrow-right-limit.png",
":/arrows/arrow-right.png",
":/arrows/arrow-top.png",
":/arrows/arrow-up-limit.png",
":/arrows/arrow-up.png",
":/auto-hide/close.png",
":/auto-hide/expand-active.png",
":/auto-hide/expand.png",
":/auto-hide/floating.png",
":/auto-hide/hide.png",
":/auto-hide/left-bottom.png",
":/auto-hide/left-top.png",
":/auto-hide/placement.png",
":/auto-hide/right-bottom.png",
":/auto-hide/right-top.png",
":/auto-hide/stick-active.png",
":/auto-hide/stick.png",
":/browser/collapse.png",
":/browser/delete-multiple.png",
":/browser/delete.png",
":/browser/disable.png",
":/browser/disabled.png",
":/browser/document.png",
":/browser/edit.png",
":/browser/enable-multiple.png",
":/browser/enable.png",
":/browser/enabled.png",
":/browser/expand.png",
":/browser/launch.png",
":/browser/main-view.png",
":/browser/move-bottom.png",
":/browser/move-down.png",
":/browser/move-top.png",
":/browser/move-up.png",
":/browser/picture.png",
":/browser/preview.png",
":/browser/select-file-1.png",
":/browser/select-file.png",
":/browser/select-preview.png",
":/browser/select-view.png",
":/browser/select.png",
":/bullets/bullet-ball-blue.png",
":/bullets/bullet-ball-glass-blue.png",
":/bullets/bullet-ball-glass-green.png",
":/bullets/bullet-ball-glass-grey.png",
":/bullets/bullet-ball-glass-red.png",
":/bullets/bullet-ball-glass-yellow.png",
":/bullets/bullet-ball-gray.png",
":/bullets/bullet-ball-green.png",
":/bullets/bullet-ball-orange.png",
":/bullets/bullet-ball-red.png",
":/bullets/bullet-ball-yellow.png",
":/bullets/bullet-ball.png",
":/bullets/bullet-square-blue.png",
":/bullets/bullet-square-gray.png",
":/bullets/bullet-square-green.png",
":/bullets/bullet-square-orange.png",
":/bullets/bullet-square-red.png",
":/bullets/bullet-square-yellow.png",
":/bullets/bullet-square.png",
":/bullets/bullet-star-blue.png",
":/bullets/bullet-star-gray.png",
":/bullets/bullet-star-green.png",
":/bullets/bullet-star-orange.png",
":/bullets/bullet-star-red.png",
":/bullets/bullet-star-yellow.png",
":/bullets/bullet-star.png",
":/bullets/bullet-triangle-blue.png",
":/bullets/bullet-triangle-gray.png",
":/bullets/bullet-triangle-green.png",
":/bullets/bullet-triangle-orange.png",
":/bullets/bullet-triangle-red.png",
":/bullets/bullet-triangle-yellow.png",
":/bullets/bullet-triangle.png",
":/cursors/accept.png",
":/cursors/accept_black.png",
":/cursors/add.png",
":/cursors/add_black.png",
":/cursors/arrow.png",
":/cursors/arrow_black.png",
":/cursors/arrow_black_shadow.png",
":/cursors/arrow_shadow.png",
":/cursors/checkmark.png",
":/cursors/circle_minus.png",
":/cursors/circle_plus.png",
":/cursors/closed_hand.png",
":/cursors/copy.png",
":/cursors/copy_black.png",
":/cursors/copy_view.png",
":/cursors/copy_view_black.png",
":/cursors/crossmark.png",
":/cursors/down_arrow.png",
":/cursors/drag_down.png",
":/cursors/drag_down_add.png",
":/cursors/drag_down_add_black.png",
":/cursors/drag_down_black.png",
":/cursors/iarrow.png",
":/cursors/iarrow_black.png",
":/cursors/left_arrow.png",
":/cursors/open_hand.png",
":/cursors/pointing_hand.png",
":/cursors/reject.png",
":/cursors/reject_black.png",
":/cursors/right_arrow.png",
":/cursors/set_mask.png",
":/cursors/set_mask_black.png",
":/cursors/set_mask_inverted.png",
":/cursors/set_mask_inverted_black.png",
":/cursors/square_minus.png",
":/cursors/square_plus.png",
":/cursors/up_arrow.png",
":/cursors/watch.png",
":/cursors/view/bidi_pan.png",
":/cursors/view/center.png",
":/cursors/view/center_active.png",
":/cursors/view/dynamic.png",
":/cursors/view/edit_preview.png",
":/cursors/view/edit_preview_active.png",
":/cursors/view/horz_pan.png",
":/cursors/view/horz_resize.png",
":/cursors/view/horz_resize_active.png",
":/cursors/view/lbrt_resize.png",
":/cursors/view/lbrt_resize_active.png",
":/cursors/view/ltrb_resize.png",
":/cursors/view/ltrb_resize_active.png",
":/cursors/view/move_preview.png",
":/cursors/view/move_preview_active.png",
":/cursors/view/new_preview.png",
":/cursors/view/new_preview_active.png",
":/cursors/view/pan.png",
":/cursors/view/readout.png",
":/cursors/view/readout_active.png",
":/cursors/view/vert_pan.png",
":/cursors/view/vert_resize.png",
":/cursors/view/vert_resize_active.png",
":/cursors/view/zoom_in.png",
":/cursors/view/zoom_in_active.png",
":/cursors/view/zoom_out.png",
":/cursors/view/zoom_out_active.png",
":/file-explorer/clear-filter.png",
":/file-explorer/copy.png",
":/file-explorer/cut.png",
":/file-explorer/delete.png",
":/file-explorer/file-explorer-icon.png",
":/file-explorer/file-explorer-icon.svg",
":/file-explorer/file-explorer-window-icon.png",
":/file-explorer/folder-new.png",
":/file-explorer/hidden-files.png",
":/file-explorer/open.png",
":/file-explorer/options.png",
":/file-explorer/paste.png",
":/file-explorer/read-only.png",
":/file-explorer/read-write.png",
":/file-explorer/rename.png",
":/file-format/bmp-format-icon.png",
":/file-format/default-format-icon.png",
":/file-format/default-format-icon.svg",
":/file-format/fits-format-icon.png",
":/file-format/gif-format-icon.png",
":/file-format/ico-format-icon.png",
":/file-format/jp2-format-icon.png",
":/file-format/jpc-format-icon.png",
":/file-format/jpeg-format-icon.png",
":/file-format/mng-format-icon.png",
":/file-format/pbm-format-icon.png",
":/file-format/pgm-format-icon.png",
":/file-format/png-format-icon.png",
":/file-format/ppm-format-icon.png",
":/file-format/raw-format-icon.png",
":/file-format/svg-format-icon.png",
":/file-format/tga-format-icon.png",
":/file-format/tiff-format-icon.png",
":/file-format/webp-format-icon.png",
":/file-format/xbm-format-icon.png",
":/file-format/xisf-format-icon.png",
":/file-format/xpm-format-icon.png",
":/floating-window/close.png",
":/floating-window/commit.png",
":/floating-window/edit.png",
":/format-explorer/format-explorer-icon.png",
":/format-explorer/format-explorer-icon.svg",
":/format-explorer/format-explorer-window-icon.png",
":/history-explorer/history-available.png",
":/history-explorer/history-explorer-icon.png",
":/history-explorer/history-explorer-icon.svg",
":/history-explorer/history-explorer-window-icon.png",
":/history-explorer/history-forbidden.png",
":/history-explorer/history-index.png",
":/icon-tools/description-data.png",
":/icon-tools/description.png",
":/icon-tools/name.png",
":/icons/add-button.png",
":/icons/add.png",
":/icons/alarm-add.png",
":/icons/alarm-delete.png",
":/icons/alarm-error.png",
":/icons/alarm-info.png",
":/icons/alarm-ok.png",
":/icons/alarm-remove.png",
":/icons/alarm-warn.png",
":/icons/alarm.png",
":/icons/alert.png",
":/icons/align-bottom.png",
":/icons/align-center.png",
":/icons/align-horz.png",
":/icons/align-left.png",
":/icons/align-middle.png",
":/icons/align-right.png",
":/icons/align-top.png",
":/icons/application.png",
":/icons/archive.png",
":/icons/arrow-bottom.png",
":/icons/arrow-down-limit.png",
":/icons/arrow-down.png",
":/icons/arrow-left-limit.png",
":/icons/arrow-left.png",
":/icons/arrow-right-limit.png",
":/icons/arrow-right.png",
":/icons/arrow-top.png",
":/icons/arrow-up-limit.png",
":/icons/arrow-up.png",
":/icons/attach.png",
":/icons/backward.png",
":/icons/blue-note.png",
":/icons/book-open.png",
":/icons/book.png",
":/icons/bookmark.png",
":/icons/border-all.png",
":/icons/border-bold-bottom.png",
":/icons/border-bold-left.png",
":/icons/border-bold-right.png",
":/icons/border-bold-top.png",
":/icons/border-bold.png",
":/icons/border-bottom.png",
":/icons/border-diagonal1.png",
":/icons/border-diagonal2.png",
":/icons/border-double-bottom.png",
":/icons/border-double-left.png",
":/icons/border-double-right.png",
":/icons/border-double-top.png",
":/icons/border-double.png",
":/icons/border-inside-horizontal.png",
":/icons/border-inside-vertical.png",
":/icons/border-inside.png",
":/icons/border-left.png",
":/icons/border-right.png",
":/icons/border-top.png",
":/icons/border.png",
":/icons/box.png",
":/icons/brush.png",
":/icons/bug-add.png",
":/icons/bug-delete.png",
":/icons/bug-edit.png",
":/icons/bug-error.png",
":/icons/bug-info.png",
":/icons/bug-ok.png",
":/icons/bug-remove.png",
":/icons/bug-warn.png",
":/icons/bug.png",
":/icons/burn.png",
":/icons/calculator.png",
":/icons/calendar.png",
":/icons/camera.png",
":/icons/cancel.png",
":/icons/character-bold-small.png",
":/icons/character-bold.png",
":/icons/character-change-case-small.png",
":/icons/character-change-case.png",
":/icons/character-double-underline-small.png",
":/icons/character-double-underline.png",
":/icons/character-font-color.png",
":/icons/character-font-highlight-color.png",
":/icons/character-italic-small.png",
":/icons/character-italic.png",
":/icons/character-strikethrough-small.png",
":/icons/character-strikethrough.png",
":/icons/character-subscript-small.png",
":/icons/character-subscript.png",
":/icons/character-superscript-small.png",
":/icons/character-superscript.png",
":/icons/character-underline-small.png",
":/icons/character-underline.png",
":/icons/chart.png",
":/icons/check.png",
":/icons/clap.png",
":/icons/class-add.png",
":/icons/class-delete.png",
":/icons/class-error.png",
":/icons/class-info.png",
":/icons/class-new.png",
":/icons/class-ok.png",
":/icons/class-remove.png",
":/icons/class-warn.png",
":/icons/class.png",
":/icons/clear-inverted.png",
":/icons/clear.png",
":/icons/clipboard-add.png",
":/icons/clipboard-delete.png",
":/icons/clipboard-edit.png",
":/icons/clipboard-export.png",
":/icons/clipboard-import.png",
":/icons/clipboard-info.png",
":/icons/clipboard-internet.png",
":/icons/clipboard-new.png",
":/icons/clipboard-ok.png",
":/icons/clipboard-remove.png",
":/icons/clipboard-warn.png",
":/icons/clipboard.png",
":/icons/clock-add.png",
":/icons/clock-delete.png",
":/icons/clock-edit.png",
":/icons/clock-error.png",
":/icons/clock-export.png",
":/icons/clock-import.png",
":/icons/clock-info.png",
":/icons/clock-internet.png",
":/icons/clock-new.png",
":/icons/clock-ok.png",
":/icons/clock-remove.png",
":/icons/clock-warn.png",
":/icons/clock.png",
":/icons/close.png",
":/icons/cloud.png",
":/icons/clouds.png",
":/icons/color-wheel.png",
":/icons/comment-add.png",
":/icons/comment-delete.png",
":/icons/comment-edit.png",
":/icons/comment-error.png",
":/icons/comment-info.png",
":/icons/comment-new.png",
":/icons/comment-ok.png",
":/icons/comment-remove.png",
":/icons/comment-warn.png",
":/icons/comment.png",
":/icons/component-add.png",
":/icons/component-delete.png",
":/icons/component-error.png",
":/icons/component-info.png",
":/icons/component-new.png",
":/icons/component-ok.png",
":/icons/component-remove.png",
":/icons/component-warn.png",
":/icons/component.png",
":/icons/compress.png",
":/icons/computer.png",
":/icons/computers.png",
":/icons/control-bulleted-list.png",
":/icons/control-button-picture.png",
":/icons/control-button-split.png",
":/icons/control-button.png",
":/icons/control-checkbox.png",
":/icons/control-combobox.png",
":/icons/control-cursor.png",
":/icons/control-date-picker.png",
":/icons/control-datetime.png",
":/icons/control-dropdown-listbox.png",
":/icons/control-edit.png",
":/icons/control-external-item-picker.png",
":/icons/control-groupbox.png",
":/icons/control-hyperlink.png",
":/icons/control-icon.png",
":/icons/control-ink-picture.png",
":/icons/control-ip-address.png",
":/icons/control-label.png",
":/icons/control-list.png",
":/icons/control-listbox.png",
":/icons/control-menu.png",
":/icons/control-multiple-selection.png",
":/icons/control-network-address.png",
":/icons/control-numbered-list.png",
":/icons/control-password.png",
":/icons/control-picture.png",
":/icons/control-plain-list.png",
":/icons/control-progressbar.png",
":/icons/control-radiobutton.png",
":/icons/control-rich-textbox.png",
":/icons/control-scrollbar-horizontal.png",
":/icons/control-scrollbar-vertical.png",
":/icons/control-scrollbox.png",
":/icons/control-signature-line.png",
":/icons/control-slider.png",
":/icons/control-spinbox.png",
":/icons/control-tabbox.png",
":/icons/control-treebox.png",
":/icons/control.png",
":/icons/controls-toolbox.png",
":/icons/copy.png",
":/icons/cut.png",
":/icons/database.png",
":/icons/datasheet.png",
":/icons/debug-break-all.png",
":/icons/debug-breakpoint-disable.png",
":/icons/debug-breakpoint.png",
":/icons/debug-breakpoints.png",
":/icons/debug-restart.png",
":/icons/debug-start.png",
":/icons/debug-step-into.png",
":/icons/debug-step-next.png",
":/icons/debug-step-out.png",
":/icons/debug-step-over.png",
":/icons/debug-stop.png",
":/icons/delete-button.png",
":/icons/delete.png",
":/icons/deploy.png",
":/icons/design.png",
":/icons/diagram.png",
":/icons/disc.png",
":/icons/document-add.png",
":/icons/document-arrow-down.png",
":/icons/document-arrow-left-right.png",
":/icons/document-arrow-left.png",
":/icons/document-arrow-right.png",
":/icons/document-arrow-up-down.png",
":/icons/document-arrow-up.png",
":/icons/document-blue.png",
":/icons/document-c.png",
":/icons/document-check.png",
":/icons/document-close.png",
":/icons/document-cpp.png",
":/icons/document-css.png",
":/icons/document-csv.png",
":/icons/document-delete.png",
":/icons/document-download.png",
":/icons/document-edit.png",
":/icons/document-error.png",
":/icons/document-execute.png",
":/icons/document-export.png",
":/icons/document-find.png",
":/icons/document-flat.png",
":/icons/document-font.png",
":/icons/document-gear.png",
":/icons/document-green.png",
":/icons/document-h.png",
":/icons/document-help.png",
":/icons/document-import.png",
":/icons/document-info.png",
":/icons/document-internet.png",
":/icons/document-js.png",
":/icons/document-lanscape.png",
":/icons/document-link.png",
":/icons/document-mail.png",
":/icons/document-math.png",
":/icons/document-new.png",
":/icons/document-ods.png",
":/icons/document-ok.png",
":/icons/document-open.png",
":/icons/document-perl.png",
":/icons/document-php.png",
":/icons/document-print.png",
":/icons/document-python.png",
":/icons/document-red.png",
":/icons/document-refresh.png",
":/icons/document-remove.png",
":/icons/document-save.png",
":/icons/document-small.png",
":/icons/document-spreadsheet.png",
":/icons/document-text-add.png",
":/icons/document-text-delete.png",
":/icons/document-text-edit.png",
":/icons/document-text-error.png",
":/icons/document-text-export.png",
":/icons/document-text-import.png",
":/icons/document-text-info.png",
":/icons/document-text-internet.png",
":/icons/document-text-new.png",
":/icons/document-text-ok.png",
":/icons/document-text-picture.png",
":/icons/document-text-remove.png",
":/icons/document-text-warn.png",
":/icons/document-text.png",
":/icons/document-up.png",
":/icons/document-update.png",
":/icons/document-upload.png",
":/icons/document-warn.png",
":/icons/document.png",
":/icons/documents-add.png",
":/icons/documents-delete.png",
":/icons/documents-edit.png",
":/icons/documents-error.png",
":/icons/documents-export.png",
":/icons/documents-import.png",
":/icons/documents-info.png",
":/icons/documents-internet.png",
":/icons/documents-new.png",
":/icons/documents-ok.png",
":/icons/documents-remove.png",
":/icons/documents-warn.png",
":/icons/documents.png",
":/icons/down.png",
":/icons/download.png",
":/icons/duplicate.png",
":/icons/eject.png",
":/icons/email.png",
":/icons/equations.png",
":/icons/error.png",
":/icons/execute.png",
":/icons/facebook.png",
":/icons/favorite-add.png",
":/icons/favorite-delete.png",
":/icons/favorite-error.png",
":/icons/favorite-info.png",
":/icons/favorite-ok.png",
":/icons/favorite-remove.png",
":/icons/favorite-warn.png",
":/icons/favorite.png",
":/icons/file-binary.png",
":/icons/file-c.png",
":/icons/file-copy.png",
":/icons/file-cpp.png",
":/icons/file-form.png",
":/icons/file-h.png",
":/icons/file-internet.png",
":/icons/file-list.png",
":/icons/file-text.png",
":/icons/file-xml.png",
":/icons/filmstrip.png",
":/icons/filter-add.png",
":/icons/filter-delete.png",
":/icons/filter-error.png",
":/icons/filter-info.png",
":/icons/filter-ok.png",
":/icons/filter-remove.png",
":/icons/filter-warn.png",
":/icons/filter.png",
":/icons/find-next.png",
":/icons/find-previous.png",
":/icons/find.png",
":/icons/flag-blue.png",
":/icons/flag-green.png",
":/icons/flag-red.png",
":/icons/flames.png",
":/icons/folder-open.png",
":/icons/folder-small.png",
":/icons/folder.png",
":/icons/font-grow.png",
":/icons/font-shrink.png",
":/icons/font.png",
":/icons/form-empty.png",
":/icons/form.png",
":/icons/forward.png",
":/icons/function-add.png",
":/icons/function-delete.png",
":/icons/function-edit.png",
":/icons/function-error.png",
":/icons/function-export.png",
":/icons/function-import.png",
":/icons/function-info.png",
":/icons/function-internet.png",
":/icons/function-new.png",
":/icons/function-ok.png",
":/icons/function-remove.png",
":/icons/function-warn.png",
":/icons/function.png",
":/icons/gear.png",
":/icons/gears.png",
":/icons/goto-first.png",
":/icons/goto-last.png",
":/icons/goto-next.png",
":/icons/goto-previous.png",
":/icons/grid-add.png",
":/icons/grid-delete.png",
":/icons/grid-error.png",
":/icons/grid-info.png",
":/icons/grid-new.png",
":/icons/grid-ok.png",
":/icons/grid-remove.png",
":/icons/grid-warn.png",
":/icons/grid.png",
":/icons/heart-add.png",
":/icons/heart-delete.png",
":/icons/heart-error.png",
":/icons/heart-info.png",
":/icons/heart-ok.png",
":/icons/heart-remove.png",
":/icons/heart-warn.png",
":/icons/heart.png",
":/icons/help.png",
":/icons/home.png",
":/icons/info.png",
":/icons/install.png",
":/icons/internet.png",
":/icons/item-add.png",
":/icons/item-delete.png",
":/icons/item-edit.png",
":/icons/item-error.png",
":/icons/item-export.png",
":/icons/item-import.png",
":/icons/item-info.png",
":/icons/item-internet.png",
":/icons/item-new.png",
":/icons/item-ok.png",
":/icons/item-remove.png",
":/icons/item-warn.png",
":/icons/item.png",
":/icons/items.png",
":/icons/key.png",
":/icons/left.png",
":/icons/link.png",
":/icons/list-add.png",
":/icons/list-arrow-left.png",
":/icons/list-arrow-right.png",
":/icons/list-delete.png",
":/icons/list-edit.png",
":/icons/list-error.png",
":/icons/list-export.png",
":/icons/list-import.png",
":/icons/list-info.png",
":/icons/list-internet.png",
":/icons/list-new.png",
":/icons/list-ok.png",
":/icons/list-remove.png",
":/icons/list-warn.png",
":/icons/list.png",
":/icons/lock.png",
":/icons/mail-open.png",
":/icons/mail.png",
":/icons/media-record.png",
":/icons/media-stop.png",
":/icons/memory-add.png",
":/icons/memory-delete.png",
":/icons/memory-error.png",
":/icons/memory-info.png",
":/icons/memory-new.png",
":/icons/memory-ok.png",
":/icons/memory-remove.png",
":/icons/memory-warn.png",
":/icons/memory.png",
":/icons/move-center.png",
":/icons/move-down-limit.png",
":/icons/move-down.png",
":/icons/move-left-down-limit.png",
":/icons/move-left-down.png",
":/icons/move-left-limit.png",
":/icons/move-left-up-limit.png",
":/icons/move-left-up.png",
":/icons/move-left.png",
":/icons/move-right-down-limit.png",
":/icons/move-right-down.png",
":/icons/move-right-limit.png",
":/icons/move-right-up-limit.png",
":/icons/move-right-up.png",
":/icons/move-right.png",
":/icons/move-up-limit.png",
":/icons/move-up.png",
":/icons/movie.png",
":/icons/music.png",
":/icons/network-application.png",
":/icons/network-computer.png",
":/icons/network-database.png",
":/icons/network-document.png",
":/icons/network-folder.png",
":/icons/network-printer.png",
":/icons/next.png",
":/icons/note-add.png",
":/icons/note-delete.png",
":/icons/note-edit.png",
":/icons/note-error.png",
":/icons/note-info.png",
":/icons/note-internet.png",
":/icons/note-new.png",
":/icons/note-ok.png",
":/icons/note-remove.png",
":/icons/note-text-add.png",
":/icons/note-text-delete.png",
":/icons/note-text-edit.png",
":/icons/note-text-error.png",
":/icons/note-text-info.png",
":/icons/note-text-internet.png",
":/icons/note-text-new.png",
":/icons/note-text-ok.png",
":/icons/note-text-remove.png",
":/icons/note-text-warn.png",
":/icons/note-text.png",
":/icons/note-warn.png",
":/icons/note.png",
":/icons/notes-text.png",
":/icons/notes.png",
":/icons/ok-button.png",
":/icons/ok.png",
":/icons/operators.png",
":/icons/organization.png",
":/icons/orientation-landscape.png",
":/icons/orientation-portrait.png",
":/icons/orientation.png",
":/icons/page.png",
":/icons/paste.png",
":/icons/pause.png",
":/icons/pencil.png",
":/icons/percentage-small.png",
":/icons/percentage.png",
":/icons/picture-add.png",
":/icons/picture-brightness.png",
":/icons/picture-colors.png",
":/icons/picture-contrast.png",
":/icons/picture-crop.png",
":/icons/picture-delete.png",
":/icons/picture-edit.png",
":/icons/picture-error.png",
":/icons/picture-export.png",
":/icons/picture-flip-horizontal.png",
":/icons/picture-flip-vertical.png",
":/icons/picture-import.png",
":/icons/picture-info.png",
":/icons/picture-internet.png",
":/icons/picture-new.png",
":/icons/picture-ok.png",
":/icons/picture-remove.png",
":/icons/picture-rotate-left.png",
":/icons/picture-rotate-right.png",
":/icons/picture-scale.png",
":/icons/picture-warn.png",
":/icons/picture.png",
":/icons/pictures.png",
":/icons/piece.png",
":/icons/pin-blue.png",
":/icons/pin-green.png",
":/icons/pin-red.png",
":/icons/pin.png",
":/icons/place-blue.png",
":/icons/place-green.png",
":/icons/place-red.png",
":/icons/place.png",
":/icons/platform-android.png",
":/icons/platform-ios.png",
":/icons/platform-linux.png",
":/icons/platform-macos.png",
":/icons/platform-windows-phone.png",
":/icons/platform-windows.png",
":/icons/play.png",
":/icons/position-bring-front.png",
":/icons/position-send-back.png",
":/icons/position.png",
":/icons/power.png",
":/icons/previous.png",
":/icons/print-preview.png",
":/icons/print-setup.png",
":/icons/print.png",
":/icons/procedure-add.png",
":/icons/procedure-delay.png",
":/icons/procedure-delete.png",
":/icons/procedure-edit.png",
":/icons/procedure-error.png",
":/icons/procedure-export.png",
":/icons/procedure-import.png",
":/icons/procedure-info.png",
":/icons/procedure-internet.png",
":/icons/procedure-new.png",
":/icons/procedure-ok.png",
":/icons/procedure-remove.png",
":/icons/procedure-warn.png",
":/icons/procedure.png",
":/icons/process-add.png",
":/icons/process-delay.png",
":/icons/process-delete.png",
":/icons/process-error.png",
":/icons/process-info.png",
":/icons/process-new.png",
":/icons/process-ok.png",
":/icons/process-remove.png",
":/icons/process-warn.png",
":/icons/process.png",
":/icons/processes.png",
":/icons/properties.png",
":/icons/queries.png",
":/icons/query-medium.png",
":/icons/query-small.png",
":/icons/query.png",
":/icons/record.png",
":/icons/redo.png",
":/icons/refresh.png",
":/icons/relations.png",
":/icons/reload.png",
":/icons/remove-button.png",
":/icons/remove.png",
":/icons/rename.png",
":/icons/repeat.png",
":/icons/replace-text.png",
":/icons/replace.png",
":/icons/report-open.png",
":/icons/report.png",
":/icons/resources.png",
":/icons/right.png",
":/icons/rss.png",
":/icons/ruler.png",
":/icons/save-all.png",
":/icons/save-as.png",
":/icons/save-error.png",
":/icons/save-internet.png",
":/icons/save-ok.png",
":/icons/save-warn.png",
":/icons/save.png",
":/icons/screen.png",
":/icons/search.png",
":/icons/secure.png",
":/icons/select-all.png",
":/icons/select-color.png",
":/icons/select-file.png",
":/icons/select-invert.png",
":/icons/select-none.png",
":/icons/select-preview.png",
":/icons/select-view.png",
":/icons/select.png",
":/icons/selection.png",
":/icons/server-medium.png",
":/icons/server-small.png",
":/icons/server.png",
":/icons/settings.png",
":/icons/share.png",
":/icons/shuffle.png",
":/icons/slide.png",
":/icons/slides.png",
":/icons/slideshow.png",
":/icons/sort-down.png",
":/icons/sort-up.png",
":/icons/sort.png",
":/icons/speaker.png",
":/icons/spell-check.png",
":/icons/star-empty.png",
":/icons/star.png",
":/icons/statistics.png",
":/icons/step-backward.png",
":/icons/step-forward.png",
":/icons/stop.png",
":/icons/styles.png",
":/icons/symbols.png",
":/icons/tab-add.png",
":/icons/tab-arrow-left.png",
":/icons/tab-arrow-right.png",
":/icons/tab-delete.png",
":/icons/tab-edit.png",
":/icons/tab-error.png",
":/icons/tab-export.png",
":/icons/tab-import.png",
":/icons/tab-info.png",
":/icons/tab-internet.png",
":/icons/tab-new.png",
":/icons/tab-ok.png",
":/icons/tab-remove.png",
":/icons/tab-warn.png",
":/icons/tab.png",
":/icons/table-add.png",
":/icons/table-arrow-down.png",
":/icons/table-arrow-left.png",
":/icons/table-arrow-right.png",
":/icons/table-arrow-up.png",
":/icons/table-burn.png",
":/icons/table-cell.png",
":/icons/table-column.png",
":/icons/table-delete.png",
":/icons/table-download.png",
":/icons/table-edit.png",
":/icons/table-error.png",
":/icons/table-export.png",
":/icons/table-gear.png",
":/icons/table-import.png",
":/icons/table-info.png",
":/icons/table-internet.png",
":/icons/table-new.png",
":/icons/table-ok.png",
":/icons/table-query.png",
":/icons/table-remove.png",
":/icons/table-row.png",
":/icons/table-save.png",
":/icons/table-update.png",
":/icons/table-upload.png",
":/icons/table-warn.png",
":/icons/table.png",
":/icons/tables.png",
":/icons/tabs-add.png",
":/icons/tabs-delete.png",
":/icons/tabs-edit.png",
":/icons/tabs-error.png",
":/icons/tabs-export.png",
":/icons/tabs-import.png",
":/icons/tabs-info.png",
":/icons/tabs-new.png",
":/icons/tabs-ok.png",
":/icons/tabs-remove.png",
":/icons/tabs-warn.png",
":/icons/tabs.png",
":/icons/tag-blue.png",
":/icons/tag-green.png",
":/icons/tag-red.png",
":/icons/tag.png",
":/icons/text-align-center.png",
":/icons/text-align-justified.png",
":/icons/text-align-left.png",
":/icons/text-align-right.png",
":/icons/text.png",
":/icons/track-down.png",
":/icons/track-left.png",
":/icons/track-right.png",
":/icons/track-up.png",
":/icons/track.png",
":/icons/trash.png",
":/icons/travel.png",
":/icons/tree.png",
":/icons/tv.png",
":/icons/twitter.png",
":/icons/undo.png",
":/icons/uninstall.png",
":/icons/unlock.png",
":/icons/up.png",
":/icons/upload.png",
":/icons/user.png",
":/icons/view-draft.png",
":/icons/view-full-screen-reading.png",
":/icons/view-full-screen.png",
":/icons/view-outline.png",
":/icons/view-page-100percent.png",
":/icons/view-page-four.png",
":/icons/view-page-layout.png",
":/icons/view-page-one.png",
":/icons/view-page-two.png",
":/icons/view-page-whole.png",
":/icons/view-page-width.png",
":/icons/volume.png",
":/icons/warning.png",
":/icons/watermark.png",
":/icons/webcam.png",
":/icons/window-add.png",
":/icons/window-arrange-horz.png",
":/icons/window-arrange-vert.png",
":/icons/window-arrow-left.png",
":/icons/window-arrow-right.png",
":/icons/window-close-all.png",
":/icons/window-close.png",
":/icons/window-delete.png",
":/icons/window-edit.png",
":/icons/window-error.png",
":/icons/window-export.png",
":/icons/window-import.png",
":/icons/window-info.png",
":/icons/window-internet.png",
":/icons/window-new.png",
":/icons/window-ok.png",
":/icons/window-remove.png",
":/icons/window-small.png",
":/icons/window-split.png",
":/icons/window-text.png",
":/icons/window-warn.png",
":/icons/window.png",
":/icons/windows-add.png",
":/icons/windows-close.png",
":/icons/windows-delete.png",
":/icons/windows-edit.png",
":/icons/windows-error.png",
":/icons/windows-export.png",
":/icons/windows-import.png",
":/icons/windows-info.png",
":/icons/windows-new.png",
":/icons/windows-ok.png",
":/icons/windows-remove.png",
":/icons/windows-warn.png",
":/icons/windows.png",
":/icons/wrap.png",
":/icons/wrench.png",
":/icons/write.png",
":/icons/zoom-1-1.png",
":/icons/zoom-1-2.png",
":/icons/zoom-2-1.png",
":/icons/zoom-in.png",
":/icons/zoom-out.png",
":/icons/zoom.png",
":/image-container/absolute-paths.png",
":/image-container/add-files.png",
":/image-container/add-item.png",
":/image-container/add-views.png",
":/image-container/disable-files.png",
":/image-container/disable-views.png",
":/image-container/edit-mask.png",
":/image-container/help.png",
":/image-container/image-container-icon.png",
":/image-container/relative-paths.png",
":/image-window/fit-view-active.png",
":/image-window/fit-view.png",
":/image-window/transparent-cross-large.png",
":/image-window/transparent-cross-medium.png",
":/image-window/transparent-cross-small.png",
":/image-window/transparent-diag-large.png",
":/image-window/transparent-diag-medium.png",
":/image-window/transparent-diag-small.png",
":/image-window/transparent-large.png",
":/image-window/transparent-medium.png",
":/image-window/transparent-small.png",
":/image-window/transparent.png",
":/image-window/zoom-1-1-active.png",
":/image-window/zoom-1-1.png",
":/image-window/zoom-best-fit-active.png",
":/image-window/zoom-best-fit.png",
":/image-window/zoom-fit-active.png",
":/image-window/zoom-fit.png",
":/messages/check.png",
":/messages/error.png",
":/messages/information.png",
":/messages/stop.png",
":/messages/warning.png",
":/object-explorer/constant.svg",
":/object-explorer/constructor.svg",
":/object-explorer/event-handler.svg",
":/object-explorer/internal-object-inherited.svg",
":/object-explorer/internal-object.svg",
":/object-explorer/method.svg",
":/object-explorer/object-explorer-icon.png",
":/object-explorer/object-explorer-icon.svg",
":/object-explorer/object-explorer-window-icon.png",
":/object-explorer/read-only-property.svg",
":/object-explorer/read-write-property.svg",
":/object-explorer/standard-object-inherited.svg",
":/object-explorer/standard-object.svg",
":/planets/asteroid.png",
":/planets/earth.png",
":/planets/jupiter.png",
":/planets/moon.png",
":/planets/orbit.png",
":/planets/planet.png",
":/planets/saturn.png",
":/planets/solar-system.png",
":/planets/sun.png",
":/print-dialog/center-horz-page.png",
":/print-dialog/center-horz.png",
":/print-dialog/center-page.png",
":/print-dialog/center-vert-page.png",
":/print-dialog/center-vert.png",
":/print-dialog/center.png",
":/print-dialog/expand-horz.png",
":/print-dialog/expand-vert.png",
":/print-dialog/landscape.png",
":/print-dialog/left-bottom.png",
":/print-dialog/left-top.png",
":/print-dialog/portrait.png",
":/print-dialog/right-bottom.png",
":/print-dialog/right-top.png",
":/process/default-process-icon.png",
":/process/default-process-icon.svg",
":/process/execute-global.png",
":/process/execute-view.png",
":/process/execute.png",
":/process/gear.png",
":/process/instance-id.png",
":/process/instance-info.png",
":/process/instance-source.png",
":/process/launch.png",
":/process-console/pause-abort.png",
":/process-console/process-console-icon.png",
":/process-console/process-console-icon.svg",
":/process-console/process-console-window-icon.png",
":/process-container/process-container-icon.png",
":/process-explorer/add-to-favorites.png",
":/process-explorer/browse-documentation.png",
":/process-explorer/browse-properties.png",
":/process-explorer/process-explorer-icon.png",
":/process-explorer/process-explorer-icon.svg",
":/process-explorer/process-explorer-window-icon.png",
":/process-explorer/remove-from-favorites.png",
":/process-interface/apply-global.png",
":/process-interface/apply.png",
":/process-interface/browse-documentation.png",
":/process-interface/cancel.png",
":/process-interface/clear.png",
":/process-interface/contract-vert.png",
":/process-interface/contract.png",
":/process-interface/diagnostics.png",
":/process-interface/edit-preferences.png",
":/process-interface/edit-source-code.png",
":/process-interface/execute.png",
":/process-interface/expand-vert.png",
":/process-interface/expand.png",
":/process-interface/load.png",
":/process-interface/new-instance.png",
":/process-interface/next.png",
":/process-interface/previous.png",
":/process-interface/real-time-active.png",
":/process-interface/real-time.png",
":/process-interface/reset.png",
":/process-interface/save.png",
":/process-interface/track-view-active.png",
":/process-interface/track-view.png",
":/qss/border-focus.png",
":/qss/border-hover.png",
":/qss/border-pressed.png",
":/qss/border.png",
":/qss/branch-closed.png",
":/qss/branch-open.png",
":/qss/checkbox-checked-hover.png",
":/qss/checkbox-checked-pressed.png",
":/qss/checkbox-checked.png",
":/qss/checkbox-disabled-checked.png",
":/qss/checkbox-disabled-indeterminate.png",
":/qss/checkbox-disabled-unchecked.png",
":/qss/checkbox-indeterminate-hover.png",
":/qss/checkbox-indeterminate-pressed.png",
":/qss/checkbox-indeterminate.png",
":/qss/checkbox-unchecked-hover.png",
":/qss/checkbox-unchecked-pressed.png",
":/qss/checkbox-unchecked.png",
":/qss/combobox-disabled-down-arrow.png",
":/qss/combobox-down-arrow-dark.png",
":/qss/combobox-down-arrow-light.png",
":/qss/header-down-arrow-dark.png",
":/qss/header-up-arrow-dark.png",
":/qss/menu-checked.png",
":/qss/menu-disabled-checked.png",
":/qss/messagebox-critical-icon.png",
":/qss/messagebox-information-icon.png",
":/qss/messagebox-question-icon.png",
":/qss/messagebox-wait-icon.png",
":/qss/messagebox-warning-icon.png",
":/qss/radiobutton-checked-hover.png",
":/qss/radiobutton-checked-pressed.png",
":/qss/radiobutton-checked.png",
":/qss/radiobutton-disabled-checked.png",
":/qss/radiobutton-disabled-unchecked.png",
":/qss/radiobutton-unchecked-hover.png",
":/qss/radiobutton-unchecked-pressed.png",
":/qss/radiobutton-unchecked.png",
":/qss/scrollbar-down-arrow-dark.png",
":/qss/scrollbar-down-arrow-light.png",
":/qss/scrollbar-left-arrow-dark.png",
":/qss/scrollbar-left-arrow-light.png",
":/qss/scrollbar-right-arrow-dark.png",
":/qss/scrollbar-right-arrow-light.png",
":/qss/scrollbar-up-arrow-dark.png",
":/qss/scrollbar-up-arrow-light.png",
":/qss/size-grip.png",
":/qss/slider-disabled-handle.png",
":/qss/slider-handle-hover.png",
":/qss/slider-handle.png",
":/qss/spinbox-disabled-down-arrow.png",
":/qss/spinbox-disabled-up-arrow.png",
":/qss/spinbox-down-arrow-dark.png",
":/qss/spinbox-down-arrow-light.png",
":/qss/spinbox-up-arrow-dark.png",
":/qss/spinbox-up-arrow-light.png",
":/qss/test.png",
":/qss/toolbar-handle-horizontal.png",
":/qss/toolbar-handle-vertical.png",
":/qss/toolbar-handle.png",
":/qss/treeview-branch-closed-dark.png",
":/qss/treeview-branch-closed-light.png",
":/qss/treeview-branch-end.png",
":/qss/treeview-branch-line-children-end.png",
":/qss/treeview-branch-line-children.png",
":/qss/treeview-branch-line.png",
":/qss/treeview-branch-more.png",
":/qss/treeview-branch-open-dark.png",
":/qss/treeview-branch-open-light.png",
":/real-time-preview/alpha-active.png",
":/real-time-preview/alpha.png",
":/real-time-preview/blue-active.png",
":/real-time-preview/blue.png",
":/real-time-preview/busy-01.png",
":/real-time-preview/busy-02.png",
":/real-time-preview/busy-03.png",
":/real-time-preview/busy-04.png",
":/real-time-preview/busy-05.png",
":/real-time-preview/busy-06.png",
":/real-time-preview/busy-07.png",
":/real-time-preview/busy-08.png",
":/real-time-preview/goto-owner.png",
":/real-time-preview/green-active.png",
":/real-time-preview/green.png",
":/real-time-preview/mask-active.png",
":/real-time-preview/mask.png",
":/real-time-preview/real-time-active.png",
":/real-time-preview/real-time-preview-icon-active.png",
":/real-time-preview/real-time-preview-icon.png",
":/real-time-preview/real-time-preview-icon.svg",
":/real-time-preview/real-time-preview-window-icon-active.png",
":/real-time-preview/real-time-preview-window-icon.png",
":/real-time-preview/real-time.png",
":/real-time-preview/red-active.png",
":/real-time-preview/red.png",
":/real-time-preview/rgbk-active.png",
":/real-time-preview/rgbk.png",
":/real-time-preview/stay-on-top-active.png",
":/real-time-preview/stay-on-top.png",
":/real-time-preview/take-snapshot.png",
":/real-time-preview/transparency-active.png",
":/real-time-preview/transparency.png",
":/script/script-icon.png",
":/script-editor/block-selection.png",
":/script-editor/bookmark-delete.png",
":/script-editor/bookmark-next.png",
":/script-editor/bookmark-previous.png",
":/script-editor/bookmark.png",
":/script-editor/check-syntax.png",
":/script-editor/clear-cache.png",
":/script-editor/close.png",
":/script-editor/compile.png",
":/script-editor/copy.png",
":/script-editor/cut.png",
":/script-editor/delete.png",
":/script-editor/document-cxx.png",
":/script-editor/document-generic.png",
":/script-editor/document-h.png",
":/script-editor/document-js.png",
":/script-editor/document-jsh.png",
":/script-editor/document-pidoc.png",
":/script-editor/document-pmath.png",
":/script-editor/document-py.png",
":/script-editor/document-scp.png",
":/script-editor/document-txt.png",
":/script-editor/document-xml.png",
":/script-editor/execute.png",
":/script-editor/export-html.png",
":/script-editor/export-odf.png",
":/script-editor/export-pdf.png",
":/script-editor/find-next.png",
":/script-editor/find-previous.png",
":/script-editor/find.png",
":/script-editor/goto-line.png",
":/script-editor/join-lines.png",
":/script-editor/lowercase.png",
":/script-editor/match-parenthesis.png",
":/script-editor/modified-document.png",
":/script-editor/new-document-js.png",
":/script-editor/new-document.png",
":/script-editor/open.png",
":/script-editor/paste.png",
":/script-editor/preferences.png",
":/script-editor/print.png",
":/script-editor/redo.png",
":/script-editor/replace.png",
":/script-editor/reset-runtime.png",
":/script-editor/save-all.png",
":/script-editor/save-as.png",
":/script-editor/save.png",
":/script-editor/script-editor-icon.png",
":/script-editor/script-editor-icon.svg",
":/script-editor/script-editor-window-icon.png",
":/script-editor/selection.png",
":/script-editor/sort-lines.png",
":/script-editor/undo.png",
":/script-editor/unmodified-document.png",
":/script-editor/uppercase.png",
":/script-editor/word-wrap.png",
":/shapes/shape-sphere-blue.png",
":/shapes/shape-sphere-gray.png",
":/shapes/shape-sphere-green.png",
":/shapes/shape-sphere-red.png",
":/splash/activation-platform-logo-v.png",
":/splash/splash-about.png",
":/splash/splash-ack.png",
":/splash/splash.png",
":/toolbar/edit-copy-view-to-clipboard.png",
":/toolbar/edit-new-image-from-clipboard.png",
":/toolbar/edit-purge-clipboard.png",
":/toolbar/edit-restore-messages.png",
":/toolbar/favorite.png",
":/toolbar/file-clear-recent.png",
":/toolbar/file-close-all-in-workspace.png",
":/toolbar/file-close-all.png",
":/toolbar/file-close.png",
":/toolbar/file-exit.png",
":/toolbar/file-open-copy.png",
":/toolbar/file-open-location.png",
":/toolbar/file-open-recent.png",
":/toolbar/file-open.png",
":/toolbar/file-print.png",
":/toolbar/file-printer-color-management.png",
":/toolbar/file-printer-setup.png",
":/toolbar/file-project-load-empty.png",
":/toolbar/file-project-load.png",
":/toolbar/file-project-metadata.png",
":/toolbar/file-project-save.png",
":/toolbar/file-project.png",
":/toolbar/file-save-as.png",
":/toolbar/file-save.png",
":/toolbar/image-color-management.png",
":/toolbar/image-color-proofing.png",
":/toolbar/image-display-alpha.png",
":/toolbar/image-display-black.png",
":/toolbar/image-display-blue.png",
":/toolbar/image-display-chrominance.png",
":/toolbar/image-display-cie-a.png",
":/toolbar/image-display-cie-b.png",
":/toolbar/image-display-green.png",
":/toolbar/image-display-hue.png",
":/toolbar/image-display-luminance.png",
":/toolbar/image-display-red.png",
":/toolbar/image-display-rgb.png",
":/toolbar/image-display-saturation.png",
":/toolbar/image-display-value.png",
":/toolbar/image-display-white.png",
":/toolbar/image-duplicate.png",
":/toolbar/image-gamut-check.png",
":/toolbar/image-identifier.png",
":/toolbar/image-mode-center.png",
":/toolbar/image-mode-dynamic.png",
":/toolbar/image-mode-edit-preview.png",
":/toolbar/image-mode-new-preview.png",
":/toolbar/image-mode-pan-horz.png",
":/toolbar/image-mode-pan-vert.png",
":/toolbar/image-mode-pan.png",
":/toolbar/image-mode-readout-highlights.png",
":/toolbar/image-mode-readout-midtones.png",
":/toolbar/image-mode-readout-normal.png",
":/toolbar/image-mode-readout-shadows.png",
":/toolbar/image-mode-readout.png",
":/toolbar/image-mode-zoom-in.png",
":/toolbar/image-mode-zoom-out.png",
":/toolbar/image-new.png",
":/toolbar/image-purge.png",
":/toolbar/image-redo-all.png",
":/toolbar/image-redo.png",
":/toolbar/image-stf-24bit.png",
":/toolbar/image-stf-auto-boost.png",
":/toolbar/image-stf-auto.png",
":/toolbar/image-stf-copy-all.png",
":/toolbar/image-stf-copy-window.png",
":/toolbar/image-stf-copy-workspace.png",
":/toolbar/image-stf-link.png",
":/toolbar/image-stf-reset-all.png",
":/toolbar/image-stf-reset-window.png",
":/toolbar/image-stf-reset-workspace.png",
":/toolbar/image-stf-reset.png",
":/toolbar/image-stf-setup.png",
":/toolbar/image-stf.png",
":/toolbar/image-transparency-black.png",
":/toolbar/image-transparency-brush.png",
":/toolbar/image-transparency-default.png",
":/toolbar/image-transparency-white.png",
":/toolbar/image-transparency.png",
":/toolbar/image-undo-all.png",
":/toolbar/image-undo.png",
":/toolbar/mask-disabled.png",
":/toolbar/mask-enabled.png",
":/toolbar/mask-inverted.png",
":/toolbar/mask-mode-multiply.png",
":/toolbar/mask-mode-overlay-blue.png",
":/toolbar/mask-mode-overlay-cyan.png",
":/toolbar/mask-mode-overlay-green.png",
":/toolbar/mask-mode-overlay-magenta.png",
":/toolbar/mask-mode-overlay-orange.png",
":/toolbar/mask-mode-overlay-red.png",
":/toolbar/mask-mode-overlay-violet.png",
":/toolbar/mask-mode-overlay-yellow.png",
":/toolbar/mask-mode-replace.png",
":/toolbar/mask-remove.png",
":/toolbar/mask-select.png",
":/toolbar/mask-visible.png",
":/toolbar/preview-clone.png",
":/toolbar/preview-delete-all.png",
":/toolbar/preview-delete.png",
":/toolbar/preview-edit.png",
":/toolbar/preview-new.png",
":/toolbar/preview-next.png",
":/toolbar/preview-previous.png",
":/toolbar/preview-redo.png",
":/toolbar/preview-reset-all.png",
":/toolbar/preview-reset.png",
":/toolbar/preview-show.png",
":/toolbar/preview-store-all.png",
":/toolbar/preview-store.png",
":/toolbar/preview-to-image.png",
":/toolbar/preview-undo.png",
":/toolbar/preview.png",
":/toolbar/previews.png",
":/toolbar/process-favorites-load.png",
":/toolbar/process-favorites-save.png",
":/toolbar/process-icons-delete-selected.png",
":/toolbar/process-icons-delete.png",
":/toolbar/process-icons-edit-info.png",
":/toolbar/process-icons-edit-source.png",
":/toolbar/process-icons-load.png",
":/toolbar/process-icons-merge.png",
":/toolbar/process-icons-save-selected.png",
":/toolbar/process-icons-save.png",
":/toolbar/process-image-container.png",
":/toolbar/process-modules-install.png",
":/toolbar/process-modules-manage.png",
":/toolbar/process-script-check.png",
":/toolbar/process-script-edit.png",
":/toolbar/process-script-run-file.png",
":/toolbar/process-script-run.png",
":/toolbar/process-scripts-feature.png",
":/toolbar/project-1.7.png",
":/toolbar/project.png",
":/toolbar/resources-about-pixinsight.png",
":/toolbar/resources-about-qt.png",
":/toolbar/resources-examples.png",
":/toolbar/resources-pixinsight-forum.png",
":/toolbar/resources-pixinsight-studios.png",
":/toolbar/resources-pixinsight-website.png",
":/toolbar/resources-repositories-manage.png",
":/toolbar/resources-tutorials.png",
":/toolbar/resources-updates-browse.png",
":/toolbar/resources-updates-check.png",
":/toolbar/resources-updates-unschedule.png",
":/toolbar/resources-video-tutorials.png",
":/toolbar/view-file-explorer.png",
":/toolbar/view-fit-window.png",
":/toolbar/view-format-explorer.png",
":/toolbar/view-full-desktop.png",
":/toolbar/view-full-screen.png",
":/toolbar/view-history-explorer.png",
":/toolbar/view-load-history-explorer.png",
":/toolbar/view-load-view-explorer.png",
":/toolbar/view-object-explorer.png",
":/toolbar/view-process-console.png",
":/toolbar/view-process-explorer.png",
":/toolbar/view-real-time-preview.png",
":/toolbar/view-script-editor.png",
":/toolbar/view-view-explorer.png",
":/toolbar/view-zoom-1-1.png",
":/toolbar/view-zoom-1-2.png",
":/toolbar/view-zoom-2-1.png",
":/toolbar/view-zoom-fit.png",
":/toolbar/view-zoom-in.png",
":/toolbar/view-zoom-optimal-fit.png",
":/toolbar/view-zoom-out.png",
":/toolbar/view-zoom.png",
":/toolbar/window-capture-screenshot.png",
":/toolbar/window-cascade-fit.png",
":/toolbar/window-cascade.png",
":/toolbar/window-icons-arrange.png",
":/toolbar/window-next.png",
":/toolbar/window-reset-maximization-limit.png",
":/toolbar/window-send-back.png",
":/toolbar/window-tile.png",
":/toolbar/window-tiny.png",
":/toolbar/window.png",
":/toolbar/windows.png",
":/toolbar/workspace-delete.png",
":/toolbar/workspace-edit.png",
":/toolbar/workspace-move.png",
":/toolbar/workspace-new.png",
":/toolbar/workspace.png",
":/update-manager/auth-lock.png",
":/update-manager/package-core-application.png",
":/update-manager/package-core-libraries.png",
":/update-manager/package-development.png",
":/update-manager/package-documentation-system.png",
":/update-manager/package-documentation.png",
":/update-manager/package-generic.png",
":/update-manager/package-module.png",
":/update-manager/package-resource.png",
":/update-manager/package-script.png",
":/update-manager/package-unknown.png",
":/update-manager/package-updater-application.png",
":/update-manager/update-downloading.png",
":/update-manager/update-error.png",
":/update-manager/update-ok.png",
":/update-manager/updated-error.png",
":/update-manager/updated-ok.png",
":/view-explorer/index.png",
":/view-explorer/spacer.png",
":/view-explorer/view-explorer-icon.png",
":/view-explorer/view-explorer-icon.svg",
":/view-explorer/view-explorer-window-icon.png",
":/wallpaper/wallpaper-1.8.5.svg",
":/web-browser/back.png",
":/web-browser/find.png",
":/web-browser/forward.png",
":/web-browser/next.png",
":/web-browser/previous.png",
":/web-browser/reload.png",
":/web-browser/stop.png",
":/web-browser/zoom-auto.png",
":/web-browser/zoom-in.png",
":/web-browser/zoom-out.png",
":/workspace/close-active.png",
":/workspace/close-inactive.png",
":/workspace/close-pressed.png",
":/workspace/close.png",
":/workspace/iconize-active.png",
":/workspace/iconize-inactive.png",
":/workspace/iconize-pressed.png",
":/workspace/iconize.png",
":/workspace/max-close-active.png",
":/workspace/max-close-inactive.png",
":/workspace/max-close-pressed.png",
":/workspace/max-close.png",
":/workspace/max-iconize-active.png",
":/workspace/max-iconize-inactive.png",
":/workspace/max-iconize-pressed.png",
":/workspace/max-iconize.png",
":/workspace/max-maximize-active.png",
":/workspace/max-maximize-inactive.png",
":/workspace/max-maximize-pressed.png",
":/workspace/max-maximize.png",
":/workspace/max-normalize-active.png",
":/workspace/max-normalize-inactive.png",
":/workspace/max-normalize-pressed.png",
":/workspace/max-normalize.png",
":/workspace/max-shade-active.png",
":/workspace/max-shade-inactive.png",
":/workspace/max-shade-pressed.png",
":/workspace/max-shade.png",
":/workspace/maximize-active.png",
":/workspace/maximize-inactive.png",
":/workspace/maximize-pressed.png",
":/workspace/maximize.png",
":/workspace/normalize-active.png",
":/workspace/normalize-inactive.png",
":/workspace/normalize-pressed.png",
":/workspace/normalize.png",
":/workspace/preview-light.png",
":/workspace/preview-small-light.png",
":/workspace/preview-small.png",
":/workspace/preview.png",
":/workspace/real-time-preview-small.png",
":/workspace/shade-active.png",
":/workspace/shade-inactive.png",
":/workspace/shade-pressed.png",
":/workspace/shade.png",
":/workspace/view-light.png",
":/workspace/view-small-light.png",
":/workspace/view-small.png",
":/workspace/view.png",
":/workspace/window-close.png",
":/workspace/window-icon-main-view.png",
":/workspace/window-icon-preview.png",
":/workspace/window-iconize.png",
":/workspace/window-maximize.png",
":/workspace/window-normalize.png",
":/workspace/window-shade.png",
":/workspace-selector/workspace-selected.png",
":/workspace-selector/workspace.png",
":/workspace/macosx/ball-blue-inactive.png",
":/workspace/macosx/ball-blue.png",
":/workspace/macosx/ball-green-inactive.png",
":/workspace/macosx/ball-green.png",
":/workspace/macosx/ball-orange-inactive.png",
":/workspace/macosx/ball-orange.png",
":/workspace/macosx/ball-red-inactive.png",
":/workspace/macosx/ball-red.png",
":/workspace/macosx/close-active.png",
":/workspace/macosx/close-inactive.png",
":/workspace/macosx/close-pressed.png",
":/workspace/macosx/close.png",
":/workspace/macosx/iconize-active.png",
":/workspace/macosx/iconize-inactive.png",
":/workspace/macosx/iconize-pressed.png",
":/workspace/macosx/iconize.png",
":/workspace/macosx/maximize-active.png",
":/workspace/macosx/maximize-inactive.png",
":/workspace/macosx/maximize-pressed.png",
":/workspace/macosx/maximize.png",
":/workspace/macosx/normalize-active.png",
":/workspace/macosx/normalize-inactive.png",
":/workspace/macosx/normalize-pressed.png",
":/workspace/macosx/normalize.png",
":/workspace/macosx/shade-active.png",
":/workspace/macosx/shade-inactive.png",
":/workspace/macosx/shade-pressed.png",
":/workspace/macosx/shade.png"
   ];

   this.cssFilePath = File.systemTempDirectory + "/pi-core-icons.css";
   this.htmlFilePath = File.systemTempDirectory + "/pi-core-icons.html";

   this.generateCSS = function( bgColor )
   {
      let css = this.scaledStyleSheet(
               "body {" +
               "   margin: 0;" +
               "   padding: 1em;" +
               "   height: 100%;" +
               "   font-family: OpenSans,\"DejaVu Sans\",Verdana,Arial,Helvetica,sans-serif;" +
               "   font-size: 8pt;" +
               "   color: " + ((bgColor > 100) ? "black" : "white") + ";" +
               "   background-color: " + format( "#%02x%02x%02x", bgColor, bgColor, bgColor ) + ";" +
               "}" +
               "table {" +
               "   border-collapse: collapse;" +
               "   width: 100%;" +
               "}" +
               "td {" +
               "   border: 1px solid #a0a0a0;" +
               "   padding-top: 0.50em;" +
               "   padding-bottom: 0.50em;" +
               "   padding-left: 0.55em;" +
               "   padding-right: 0.55em;" +
               "}\n" );

      File.writeTextFile( this.cssFilePath, css );
   };

   this.generateHTML = function( tableColumns )
   {
      let html = this.scaledStyleSheet( "<!DOCTYPE html>\n" +
               "<html>\n" +
               "<head>\n" +
               "<meta charset=\"utf-8\">\n" +
               "<link type=\"text/css\" href=\"file:\/\/" + this.cssFilePath + "\" rel=\"stylesheet\"/>" +
               "</head>\n" +
               "<body>\n" +
               "<table>\n" );

      for ( let i = 0; i < this.coreIcons.length; )
      {
         html += "<tr>\n";
         for ( let c = 0; c < tableColumns && i < this.coreIcons.length; ++c, ++i )
         {
            let iconResource = (File.extractSuffix( this.coreIcons[i] ) != ".svg") ? // don't scale vector resources
                                    this.scaledResource( this.coreIcons[i] ) : this.coreIcons[i];
            let icon = new Bitmap( iconResource );
            let iconWidth = Math.round( icon.width*this.resourcePixelRatio/this.displayPixelRatio )|0;
            let iconHeight = Math.round( icon.height*this.resourcePixelRatio/this.displayPixelRatio )|0;
            let imgWidth = iconWidth;
            let imgHeight = iconHeight;
            let maxSize = Math.uiScaled( this.displayPixelRatio, MAX_ICON_SIZE );
            if ( imgWidth > maxSize || imgHeight > maxSize )
            {
               let scaleFactor = maxSize/Math.max( imgWidth, imgHeight );
               imgWidth = Math.round( scaleFactor*imgWidth )|0;
               imgHeight = Math.round( scaleFactor*imgHeight )|0;
            }

            html += "<td>\n";
            html += "<img width=\"" + imgWidth.toString() + "\" " +
                      "height=\"" + imgHeight.toString() + "\" " +
                      "src=\"" + iconResource.replace( ":/", "qrc:/" ) + "\" " +
                      "title=\"" + this.coreIcons[i] + format( " (%dx%d)", iconWidth, iconHeight ) + "\"/><br/>\n";
            html += this.coreIcons[i] + format( " (%dx%d)\n", iconWidth, iconHeight );
            html += "</td>\n";
         }
         html += "</tr>\n";
      }

      html += "</table>\n" +
           "</body>\n" +
           "</html>";

      File.writeTextFile( this.htmlFilePath, html );
   };

   this.generateHTML( 4 );

   this.browser_WebView = new WebView( this );
   this.browser_WebView.loadContent( this.htmlFilePath );

   this.bkgColor_Label = new Label( this );
   this.bkgColor_Label.text = "Background color:";
   this.bkgColor_Label.textAlignment = TextAlign_Right|TextAlign_VertCenter;

   this.bkgColor_SpinBox = new SpinBox( this );
   this.bkgColor_SpinBox.minValue = 0;
   this.bkgColor_SpinBox.maxValue = 255;
   this.bkgColor_SpinBox.value = 255;
   this.bkgColor_SpinBox.onValueUpdated = function( value )
   {
      this.dialog.generateCSS( value );
      this.dialog.browser_WebView.reload();
   };

   this.close_PushButton = new PushButton( this );
   this.close_PushButton.text = "Close";
   this.close_PushButton.onClick = function()
   {
      this.dialog.cancel();
   };

   this.bottom_Sizer = new HorizontalSizer;
   this.bottom_Sizer.spacing = 4;
   this.bottom_Sizer.add( this.bkgColor_Label );
   this.bottom_Sizer.add( this.bkgColor_SpinBox );
   this.bottom_Sizer.addStretch();
   this.bottom_Sizer.add( this.close_PushButton );

   this.bkgColor_SpinBox.onValueUpdated( this.bkgColor_SpinBox.value );

   this.sizer = new VerticalSizer;
   this.sizer.margin = 8;
   this.sizer.spacing = 8;
   this.sizer.add( this.browser_WebView, 100 );
   this.sizer.add( this.bottom_Sizer );

   this.windowTitle = TITLE + " v" + VERSION;
   this.resize( Math.uiScaled( this.displayPixelRatio, 1024 ),
                Math.uiScaled( this.displayPixelRatio,  600 ) );
}

IconBrowser.prototype = new Dialog;

console.hide();
(new IconBrowser).execute();

// ----------------------------------------------------------------------------
// EOF CoreIconsBrowser.js - Released 2019-01-19T18:43:13Z
