// ----------------------------------------------------------------------------
// PixInsight JavaScript Runtime API - PJSR Version 1.0
// ----------------------------------------------------------------------------
// MakGenMSVCProjects.js - Released 2015/11/26 08:53:10 UTC
// ----------------------------------------------------------------------------
//
// This file is part of PixInsight Makefile Generator Script version 1.100
//
// Copyright (c) 2009-2015 Pleiades Astrophoto S.L.
//
// Redistribution and use in both source and binary forms, with or without
// modification, is permitted provided that the following conditions are met:
//
// 1. All redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//
// 2. All redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//
// 3. Neither the names "PixInsight" and "Pleiades Astrophoto", nor the names
//    of their contributors, may be used to endorse or promote products derived
//    from this software without specific prior written permission. For written
//    permission, please contact info@pixinsight.com.
//
// 4. All products derived from this software, in any form whatsoever, must
//    reproduce the following acknowledgment in the end-user documentation
//    and/or other materials provided with the product:
//
//    "This product is based on software from the PixInsight project, developed
//    by Pleiades Astrophoto and its contributors (http://pixinsight.com/)."
//
//    Alternatively, if that is where third-party acknowledgments normally
//    appear, this acknowledgment must be reproduced in the product itself.
//
// THIS SOFTWARE IS PROVIDED BY PLEIADES ASTROPHOTO AND ITS CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
// TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL PLEIADES ASTROPHOTO OR ITS
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, BUSINESS
// INTERRUPTION; PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; AND LOSS OF USE,
// DATA OR PROFITS) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
// CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
// POSSIBILITY OF SUCH DAMAGE.
// ----------------------------------------------------------------------------

/*
 * PixInsight Makefile Generator
 *
 * Automatic generation of PCL makefiles and projects for FreeBSD, Linux,
 * Mac OS X and Windows platforms.
 *
 * Copyright (c) 2009-2015, Pleiades Astrophoto S.L. All Rights Reserved.
 * Written by Juan Conejero (PTeam)
 *
 * Generation of project files for Microsoft Visual C++ 2008, 2010, 2012 and
 * 2013 (.vcproj and .vcxproj files).
 */

function MSVCxxAll( F, P )
{
   /*
    * VC++ 2008/2010/2012 projects are no longer generated by default
    */
   //MSVCxx9( F, P );
   //MSVCxx10( F, P );
   //MSVCxx11( F, P );
   if ( P.cleanUpPreviousBuilds )
      for ( var i = 9; i <= 11; ++i )
      {
         var d = P.vccBuildDirectory( F.baseDirectory, i );
         if ( File.directoryExists( d ) )
            removeDirectory( d );
      }

   MSVCxx12( F, P );
}

function MSVCxxHeader( f, F, P, vcVersion )
{
   f.outTextLn( "<?xml version=\"1.0\" encoding=\"utf-8\"?>" );
   f.outTextLn( "<!--" );
   f.outTextLn( "######################################################################" );
   f.outTextLn( "# PixInsight Makefile Generator Script v" + VERSION );
   f.outTextLn( "# Copyright (C) 2009-2015 Pleiades Astrophoto" );
   f.outTextLn( "######################################################################" );
   f.outTextLn( "# Automatically generated on " + (new Date( Date.now() )).toUTCString() );
   f.outTextLn( "# Project id ...... " + P.id );
   f.outTextLn( "# Project type .... " + P.type );
   f.outTextLn( "# Platform ........ " + "Windows/vc" + vcVersion.toString() );
   if ( P.extraDefinitions.length > 0 || P.winExtraDefinitions.length > 0 || P.diagnostics != 0 )
   {
      f.outTextLn( "# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++" );
      f.outTextLn( "# Additional preprocessor definitions:" );
      for ( var i = 0; i < P.extraDefinitions.length; ++i )
         f.outTextLn( "# " + P.extraDefinitions[i] );
      for ( var i = 0; i < P.winExtraDefinitions.length; ++i )
         f.outTextLn( "# " + P.winExtraDefinitions[i] );
      if ( P.diagnostics != 0 )
         f.outTextLn( "# __PCL_DIAGNOSTICS_LEVEL=" + P.diagnostics.toString() );
   }
   if ( P.extraIncludeDirs.length > 0 )
   {
      f.outTextLn( "# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++" );
      f.outTextLn( "# Additional include search directories:" );
      for ( var i = 0; i < P.extraIncludeDirs.length; ++i )
         f.outTextLn( "# " + P.extraIncludeDirs[i] );
   }
   if ( P.extraLibDirs.length > 0 )
   {
      f.outTextLn( "# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++" );
      f.outTextLn( "# Additional library search directories:" );
      for ( var i = 0; i < P.extraLibDirs.length; ++i )
         f.outTextLn( "# " + P.extraLibDirs[i] );
   }
   if ( P.extraLibraries.length > 0 )
   {
      f.outTextLn( "# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++" );
      f.outTextLn( "# Additional libraries:" );
      for ( var i = 0; i < P.extraLibraries.length; ++i )
         f.outTextLn( "# " + P.extraLibraries[i] );
   }
   f.outTextLn( "######################################################################" );
   f.outTextLn( "-->" );
}

// ----------------------------------------------------------------------------
// EOF MakGenMSVCProjects.js - Released 2015/11/26 08:53:10 UTC
